CREATE TABLE IF NOT EXISTS ads_project (
 id BIGINT PRIMARY KEY, project_no VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, story_background TEXT NULL, original_dialogue LONGTEXT NOT NULL, output_mode VARCHAR(32) NOT NULL, default_skill_version_id BIGINT NULL, status VARCHAR(32) NOT NULL, analysis_stale TINYINT NOT NULL DEFAULT 0, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_by BIGINT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL, deleted TINYINT NOT NULL DEFAULT 0, INDEX idx_ads_project_status(status)
);
CREATE TABLE IF NOT EXISTS ads_skill (
 id BIGINT PRIMARY KEY, skill_code VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, description TEXT NULL, task_type VARCHAR(40) NOT NULL, enabled TINYINT NOT NULL DEFAULT 1, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_by BIGINT NULL, updated_at DATETIME NOT NULL, deleted TINYINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS ads_skill_version (
 id BIGINT PRIMARY KEY, skill_id BIGINT NOT NULL, version_no VARCHAR(40) NOT NULL, status VARCHAR(24) NOT NULL, system_prompt_template LONGTEXT NOT NULL, input_schema_json LONGTEXT NULL, output_schema_json LONGTEXT NULL, split_rules_json LONGTEXT NULL, rewrite_rules_json LONGTEXT NULL, emotion_mapping_json LONGTEXT NULL, examples_json LONGTEXT NULL, model_parameters_json LONGTEXT NULL, test_cases_json LONGTEXT NULL, content_hash CHAR(64) NOT NULL, published_at DATETIME NULL, archived_at DATETIME NULL, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_by BIGINT NULL, updated_at DATETIME NOT NULL, deleted TINYINT NOT NULL DEFAULT 0, UNIQUE KEY uk_ads_skill_version(skill_id,version_no), INDEX idx_ads_skill_version_state(skill_id,status)
);
CREATE TABLE IF NOT EXISTS ads_analysis_run (
 id BIGINT PRIMARY KEY, run_no VARCHAR(40) NOT NULL UNIQUE, project_id BIGINT NOT NULL, project_version INT NOT NULL, skill_version_id BIGINT NOT NULL, provider_id BIGINT NULL, model_id BIGINT NULL, provider_code_snapshot VARCHAR(80) NULL, model_code_snapshot VARCHAR(120) NULL, rewrite_mode VARCHAR(24) NOT NULL, background_snapshot TEXT NULL, dialogue_snapshot LONGTEXT NOT NULL, input_hash CHAR(64) NOT NULL, prompt_hash CHAR(64) NOT NULL, model_parameters_json LONGTEXT NULL, status VARCHAR(32) NOT NULL, raw_response_json LONGTEXT NULL, candidate_result_json LONGTEXT NULL, validation_warnings_json LONGTEXT NULL, error_code VARCHAR(80) NULL, error_message VARCHAR(500) NULL, started_at DATETIME NULL, finished_at DATETIME NULL, applied_at DATETIME NULL, applied_by BIGINT NULL, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_ads_analysis_project(project_id,status)
);
CREATE TABLE IF NOT EXISTS ads_character (
 id BIGINT PRIMARY KEY, project_id BIGINT NOT NULL, character_code VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT NULL, default_provider_id BIGINT NULL, default_model_id BIGINT NULL, default_voice_id VARCHAR(160) NULL, voice_config_json LONGTEXT NULL, sort_no INT NOT NULL DEFAULT 0, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_by BIGINT NULL, updated_at DATETIME NOT NULL, deleted TINYINT NOT NULL DEFAULT 0, UNIQUE KEY uk_ads_character(project_id,character_code)
);
CREATE TABLE IF NOT EXISTS ads_dialogue_segment (
 id BIGINT PRIMARY KEY, project_id BIGINT NOT NULL, segment_no INT NOT NULL, speaker_id BIGINT NULL, speaker_name_snapshot VARCHAR(120) NULL, semantic_group VARCHAR(160) NULL, source_start INT NOT NULL, source_end INT NOT NULL, original_text TEXT NOT NULL, spoken_text TEXT NOT NULL, subtitle_text TEXT NOT NULL, emotion_json LONGTEXT NULL, tone_json LONGTEXT NULL, speed DECIMAL(6,3) NULL, volume DECIMAL(6,3) NULL, pause_before_ms INT NOT NULL DEFAULT 0, pause_after_ms INT NOT NULL DEFAULT 0, emphasis_json LONGTEXT NULL, voice_direction TEXT NULL, rewrite_mode VARCHAR(24) NULL, rewrite_level VARCHAR(24) NULL, rewrite_reason VARCHAR(1000) NULL, manual_edited TINYINT NOT NULL DEFAULT 0, audio_stale TINYINT NOT NULL DEFAULT 1, analysis_run_id BIGINT NULL, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_by BIGINT NULL, updated_at DATETIME NOT NULL, deleted TINYINT NOT NULL DEFAULT 0, UNIQUE KEY uk_ads_segment_no(project_id,segment_no,deleted), INDEX idx_ads_segment_project(project_id,segment_no)
);
CREATE TABLE IF NOT EXISTS ads_provider (
 id BIGINT PRIMARY KEY, provider_code VARCHAR(80) NOT NULL UNIQUE, display_name VARCHAR(160) NOT NULL, provider_type VARCHAR(32) NOT NULL, base_url VARCHAR(500) NULL, credential_ref VARCHAR(200) NULL, masked_credential_hint VARCHAR(80) NULL, timeout_seconds INT NOT NULL DEFAULT 120, max_concurrency INT NOT NULL DEFAULT 1, config_json LONGTEXT NULL, enabled TINYINT NOT NULL DEFAULT 1, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_by BIGINT NULL, updated_at DATETIME NOT NULL, deleted TINYINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS ads_model (
 id BIGINT PRIMARY KEY, provider_id BIGINT NOT NULL, model_code VARCHAR(120) NOT NULL, display_name VARCHAR(160) NOT NULL, model_type VARCHAR(32) NOT NULL, capabilities_json LONGTEXT NULL, default_parameters_json LONGTEXT NULL, enabled TINYINT NOT NULL DEFAULT 1, sort_no INT NOT NULL DEFAULT 0, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_by BIGINT NULL, updated_at DATETIME NOT NULL, deleted TINYINT NOT NULL DEFAULT 0, UNIQUE KEY uk_ads_model(provider_id,model_code)
);
CREATE TABLE IF NOT EXISTS ads_generation_task (
 id BIGINT PRIMARY KEY, task_no VARCHAR(40) NOT NULL UNIQUE, project_id BIGINT NOT NULL, provider_id BIGINT NOT NULL, model_id BIGINT NOT NULL, provider_code_snapshot VARCHAR(80) NOT NULL, model_code_snapshot VARCHAR(120) NOT NULL, idempotency_key VARCHAR(160) NULL, request_hash CHAR(64) NOT NULL, parameters_json LONGTEXT NULL, status VARCHAR(32) NOT NULL, total_count INT NOT NULL, success_count INT NOT NULL DEFAULT 0, failed_count INT NOT NULL DEFAULT 0, cancelled_count INT NOT NULL DEFAULT 0, progress_percent DECIMAL(5,2) NOT NULL DEFAULT 0, cancel_requested_at DATETIME NULL, started_at DATETIME NULL, finished_at DATETIME NULL, last_heartbeat_at DATETIME NULL, worker_id VARCHAR(120) NULL, error_code VARCHAR(80) NULL, error_message VARCHAR(500) NULL, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uk_ads_task_idempotency(project_id,idempotency_key), INDEX idx_ads_task_status(status,updated_at)
);
CREATE TABLE IF NOT EXISTS ads_generation_item (
 id BIGINT PRIMARY KEY, task_id BIGINT NOT NULL, item_no INT NOT NULL, segment_id BIGINT NOT NULL, segment_version INT NOT NULL, provider_id BIGINT NOT NULL, model_id BIGINT NOT NULL, provider_code_snapshot VARCHAR(80) NOT NULL, model_code_snapshot VARCHAR(120) NOT NULL, voice_id VARCHAR(160) NOT NULL, text_snapshot TEXT NOT NULL, parameters_json LONGTEXT NULL, request_hash CHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, attempt_count INT NOT NULL DEFAULT 0, max_attempts INT NOT NULL DEFAULT 3, next_retry_at DATETIME NULL, external_task_id VARCHAR(160) NULL, audio_asset_id BIGINT NULL, warnings_json LONGTEXT NULL, error_code VARCHAR(80) NULL, error_message VARCHAR(500) NULL, started_at DATETIME NULL, finished_at DATETIME NULL, version INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uk_ads_item_request(request_hash), UNIQUE KEY uk_ads_item_no(task_id,item_no), INDEX idx_ads_item_task(task_id,status)
);
CREATE TABLE IF NOT EXISTS ads_audio_asset (
 id BIGINT PRIMARY KEY, asset_no VARCHAR(40) NOT NULL UNIQUE, project_id BIGINT NOT NULL, segment_id BIGINT NULL, segment_version INT NULL, generation_task_id BIGINT NULL, asset_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, storage_provider VARCHAR(32) NOT NULL, bucket_name VARCHAR(160) NULL, object_key VARCHAR(500) NOT NULL, original_file_name VARCHAR(255) NULL, media_type VARCHAR(100) NULL, file_size_bytes BIGINT NULL, sha256 CHAR(64) NULL, duration_ms BIGINT NULL, sample_rate_hz INT NULL, bit_depth INT NULL, channels INT NULL, loudness_lufs DECIMAL(8,2) NULL, peak_dbfs DECIMAL(8,2) NULL, manifest_json LONGTEXT NULL, expires_at DATETIME NULL, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted TINYINT NOT NULL DEFAULT 0, INDEX idx_ads_asset_segment(segment_id,status), INDEX idx_ads_asset_project(project_id,created_at)
);
CREATE TABLE IF NOT EXISTS ads_export_record (
 id BIGINT PRIMARY KEY, export_no VARCHAR(40) NOT NULL UNIQUE, project_id BIGINT NOT NULL, export_type VARCHAR(24) NOT NULL, status VARCHAR(32) NOT NULL, idempotency_key VARCHAR(160) NULL, project_version INT NOT NULL, snapshot_json LONGTEXT NOT NULL, storage_provider VARCHAR(32) NULL, bucket_name VARCHAR(160) NULL, object_key VARCHAR(500) NULL, file_name VARCHAR(255) NULL, file_size_bytes BIGINT NULL, sha256 CHAR(64) NULL, error_code VARCHAR(80) NULL, error_message VARCHAR(500) NULL, started_at DATETIME NULL, finished_at DATETIME NULL, expires_at DATETIME NULL, version INT NOT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uk_ads_export_idempotency(project_id,export_type,idempotency_key)
);
CREATE TABLE IF NOT EXISTS ads_audit_log (
 id BIGINT PRIMARY KEY, project_id BIGINT NULL, actor_id BIGINT NULL, action VARCHAR(80) NOT NULL, target_type VARCHAR(80) NOT NULL, target_id VARCHAR(80) NULL, detail_json LONGTEXT NULL, trace_id VARCHAR(80) NULL, created_at DATETIME NOT NULL, INDEX idx_ads_audit_target(target_type,target_id), INDEX idx_ads_audit_project(project_id,created_at)
);
